// This file is automatically generated.  Do not edit.
#ifndef COMMON_C_MATH_CAL_PARAMS_H_
#define COMMON_C_MATH_CAL_PARAMS_H_

#include <stdint.h>

typedef struct {
  float scale;
  float bias;
  int32_t bias_count;
} CalParams32;

#endif  // COMMON_C_MATH_CAL_PARAMS_H_
