## $Header: /var/cvs/mbdyn/mbdyn/mbdyn-1.0/modules/module-aerodyn/Makefile.inc,v 1.5 2009/06/12 11:14:56 masarati Exp $
MODULE_DEPENDENCIES=mbdyn_ad.lo
# MODULE_LINK=-L. -lnewtonraphson_f90
MODULE_LINK=-L. -lkitefast
