This is makeindex, version 2.15 [TeX Live 2010] (kpathsea + Thai support).
Scanning style file ./VSM_Theory.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file VSM_Theory.acn....done (55 entries accepted, 0 rejected).
Sorting entries....done (344 comparisons).
Generating output file VSM_Theory.acr....done (51 lines written, 0 warnings).
Output written in VSM_Theory.acr.
Transcript written in VSM_Theory.alg.
